# -*- coding: utf-8 -*-
import sys, os, re, shutil, zipfile, struct, zlib
for s in (sys.stdout, sys.stderr):
    if hasattr(s, "reconfigure"): s.reconfigure(encoding="utf-8", errors="backslashreplace")

# ---------- параметры ----------
AUTHOR = "Laimusp"
MOD    = "WhiteKnuckleRU"
VER    = "1.0.1"
SUB    = AUTHOR + "-" + MOD            # папка плагина: Laimusp-WhiteKnuckleRU
WEB    = "https://github.com/%s/%s" % (AUTHOR, MOD)

# исходник BepInEx/XUAT/шрифтов/загрузчика: рабочий стек перенесён в бэкап после чистки папки игры
GAME = "C:/Users/user/WhiteKnuckleRU_devbak"
SC   = "C:/Users/user/AppData/Local/Temp/claude/C--Users-user/2a4bdbf6-80cd-46b4-b6f6-327dd24fa9f5/scratchpad"
BUILD = SC + "/build"
DIST  = BUILD + "/dist"

GROOT = GAME
GBEP  = GAME + "/BepInEx"
GPLUG = GBEP + "/plugins"
GCFG  = GBEP + "/config"
GCORE = GBEP + "/core"
GTXT  = GBEP + "/Translation/ru/Text"

DICT = "_AutoGeneratedTranslations.txt"
COMPANIONS = ["zz_ui_regex.txt", "zz_stat_regex.txt", "zz_stat_extra.txt",
              "_Substitutions.txt", "_Preprocessors.txt", "_Postprocessors.txt"]

def rm(p):
    if os.path.isdir(p): shutil.rmtree(p, ignore_errors=True)
    elif os.path.exists(p): os.remove(p)

def ensure(p):
    os.makedirs(p, exist_ok=True); return p

def keyidx(ln):
    for i, ch in enumerate(ln):
        if ch == '=' and (i == 0 or ln[i-1] != '\\'): return i
    return -1

# ---------- 1) чистка словаря (минимально и безопасно) ----------
def clean_dict():
    raw = open(GTXT + "/" + DICT, "rb").read()
    if raw[:3] == b"\xef\xbb\xbf": raw = raw[3:]          # снять BOM если вдруг
    txt = raw.decode("utf-8", "replace")
    out = []
    dropped_empty = 0
    for ln in txt.split("\n"):
        ln = ln.rstrip("\r")
        s = ln.strip()
        if s == "" or s == "=":                            # пустые строки и одинокий '='
            dropped_empty += 1; continue
        i = keyidx(ln)
        if i == 0:                                         # ключ пустой -> мусор
            dropped_empty += 1; continue
        out.append(ln)
    body = "\n".join(out) + "\n"
    return body, len(out), dropped_empty

# ---------- 2) переписать конфиг под plugin-relative пути ----------
def rewrite_config():
    cfg = open(GCFG + "/AutoTranslatorConfig.ini", "r", encoding="utf-8-sig").read()
    old = "Translation\\{Lang}"
    new = "plugins\\" + SUB + "\\Translation\\{Lang}"
    n = cfg.count(old)
    cfg = cfg.replace(old, new)
    # контроль
    assert ("Directory=plugins\\%s\\Translation\\{Lang}\\Text" % SUB) in cfg, "Directory не переписан"
    assert "Directory=Translation\\{Lang}" not in cfg, "остался старый Directory"
    assert "OverrideFontTextMeshPro=oswald_ru_sdf" in cfg, "потерян override-шрифт"
    return cfg, n

# ---------- копирование XUAT без Translators ----------
def copy_xuat(dst_plugins):
    src = GPLUG + "/XUnity.AutoTranslator"
    dst = ensure(dst_plugins + "/XUnity.AutoTranslator")
    for name in os.listdir(src):
        full = src + "/" + name
        if os.path.isdir(full):
            if name == "Translators":      # онлайн-бэкенды (+ .exe) не нужны при статическом переводе
                continue
            shutil.copytree(full, dst + "/" + name)
        else:
            shutil.copy2(full, dst + "/" + name)
    # ResourceRedirector
    shutil.copytree(GPLUG + "/XUnity.ResourceRedirector", dst_plugins + "/XUnity.ResourceRedirector")

def write_text(path, text):
    ensure(os.path.dirname(path))
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)

def put_translation(text_dir, dict_body):
    ensure(text_dir)
    write_text(text_dir + "/" + DICT, dict_body)
    for c in COMPANIONS:
        shutil.copy2(GTXT + "/" + c, text_dir + "/" + c)

# ---------- ICON 256x256 ----------
def make_icon(path):
    try:
        from PIL import Image, ImageDraw, ImageFont
        W = 256
        img = Image.new("RGB", (W, W), (24, 24, 27))
        d = ImageDraw.Draw(img)
        for y in range(W):                                  # вертикальный градиент
            t = y / (W - 1.0)
            c = (int(24 + 10*t), int(24 + 8*t), int(27 + 12*t))
            d.line([(0, y), (W, y)], fill=c)
        d.rectangle([4, 4, W-5, W-5], outline=(70, 70, 76), width=2)
        def font(sz):
            for fn in ("arialbd.ttf", "ariblk.ttf", "segoeuib.ttf"):
                try: return ImageFont.truetype("C:/Windows/Fonts/" + fn, sz)
                except Exception: pass
            return ImageFont.load_default()
        def center(txt, f, cy, fill):
            try:
                b = d.textbbox((0, 0), txt, font=f); w = b[2]-b[0]; h = b[3]-b[1]; oy = b[1]
            except Exception:
                w, h = d.textsize(txt, font=f); oy = 0
            d.text(((W-w)/2.0, cy - h/2.0 - oy), txt, font=f, fill=fill)
        center("WK", font(118), 96, (236, 236, 232))
        center("РУ", font(72), 188, (176, 65, 62))
        img.save(path, "PNG")
        return "PIL"
    except Exception as e:
        # запасной вариант: сплошной валидный PNG 256x256
        W = 256; px = bytes((26, 26, 29))
        row = b"\x00" + px * W
        rawimg = row * W
        comp = zlib.compress(rawimg, 9)
        def chunk(typ, data):
            return struct.pack(">I", len(data)) + typ + data + struct.pack(">I", zlib.crc32(typ + data) & 0xffffffff)
        png = b"\x89PNG\r\n\x1a\n"
        png += chunk(b"IHDR", struct.pack(">IIBBBBB", W, W, 8, 2, 0, 0, 0))
        png += chunk(b"IDAT", comp)
        png += chunk(b"IEND", b"")
        open(path, "wb").write(png)
        return "fallback(%s)" % type(e).__name__

# ---------- zip ----------
def zipdir(src_root, zip_path):
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as z:
        for root, dirs, files in os.walk(src_root):
            for fn in files:
                full = os.path.join(root, fn)
                arc = os.path.relpath(full, src_root).replace("\\", "/")
                z.write(full, arc)
    return os.path.getsize(zip_path)

# =================== СБОРКА ===================
rm(BUILD); ensure(BUILD); ensure(DIST)
dict_body, dict_lines, dropped = clean_dict()
cfg_text, cfg_repl = rewrite_config()
print("словарь: строк=%d, выкинуто пустых=%d | конфиг: замен путей=%d" % (dict_lines, dropped, cfg_repl))

# ---- (M) MANUAL: зеркало корня игры, всё включено ----
M = ensure(BUILD + "/manual")
# loader в корне
for f in (".doorstop_version", "doorstop_config.ini", "winhttp.dll"):
    shutil.copy2(GROOT + "/" + f, M + "/" + f)
shutil.copy2(GROOT + "/oswald_ru_sdf", M + "/oswald_ru_sdf")          # шрифт в корне -> XUAT override как сейчас
# BepInEx core (полный) + config
shutil.copytree(GCORE, M + "/BepInEx/core")
ensure(M + "/BepInEx/config")
write_text(M + "/BepInEx/config/AutoTranslatorConfig.ini", cfg_text)
shutil.copy2(GCFG + "/BepInEx.cfg", M + "/BepInEx/config/BepInEx.cfg")
shutil.copy2(GCFG + "/gravydevsupreme.xunity.resourceredirector.cfg", M + "/BepInEx/config/gravydevsupreme.xunity.resourceredirector.cfg")
# plugins: XUAT(+RR) напрямую, мой мод в подпапке
Mplug = ensure(M + "/BepInEx/plugins")
copy_xuat(Mplug)
Mmod = ensure(Mplug + "/" + SUB)
shutil.copy2(SC + "/WKSourceTranslate.dll", Mmod + "/WKSourceTranslate.dll")
shutil.copy2(SC + "/WKRusHelper.dll", Mmod + "/WKRusHelper.dll")
put_translation(Mmod + "/Translation/ru/Text", dict_body)

# ---- (T) THUNDERSTORE: override-папки в корне zip ----
T = ensure(BUILD + "/thunderstore")
Tplug = ensure(T + "/plugins")           # -> BepInEx/plugins/Laimusp-WhiteKnuckleRU/
shutil.copy2(SC + "/WKSourceTranslate.dll", Tplug + "/WKSourceTranslate.dll")
shutil.copy2(SC + "/WKRusHelper.dll", Tplug + "/WKRusHelper.dll")
shutil.copy2(GROOT + "/oswald_ru_sdf", Tplug + "/oswald_ru_sdf")       # шрифт рядом с плагином -> грузим сами
shutil.copy2(GCORE + "/XUnity.Common.dll", Tplug + "/XUnity.Common.dll")  # co-located, не в core/
copy_xuat(Tplug)
put_translation(Tplug + "/Translation/ru/Text", dict_body)
Tcfg = ensure(T + "/config")
write_text(Tcfg + "/AutoTranslatorConfig.ini", cfg_text)
shutil.copy2(GCFG + "/gravydevsupreme.xunity.resourceredirector.cfg", Tcfg + "/gravydevsupreme.xunity.resourceredirector.cfg")

# manifest / icon / docs в корне thunderstore
manifest = ('{\n'
            '  "name": "%s",\n'
            '  "version_number": "%s",\n'
            '  "website_url": "%s",\n'
            '  "description": "Unofficial Russian fan translation for White Knuckle (XUnity.AutoTranslator-based)",\n'
            '  "dependencies": [\n    "BepInEx-BepInExPack-5.4.2305"\n  ]\n'
            '}\n') % (MOD, VER, WEB)
write_text(T + "/manifest.json", manifest)
icon_mode = make_icon(T + "/icon.png")

README = open(SC + "/README_RU.md", "r", encoding="utf-8").read()
CHANGELOG = open(SC + "/CHANGELOG_RU.md", "r", encoding="utf-8").read()
LICENSE = open(SC + "/LICENSE_RU.txt", "r", encoding="utf-8").read()
write_text(T + "/README.md", README)
write_text(T + "/CHANGELOG.md", CHANGELOG)
write_text(T + "/LICENSE", LICENSE)

# ---- zip оба ----
z_manual = zipdir(M, DIST + "/%s-%s-manual.zip" % (MOD, VER))
z_thunder = zipdir(T, DIST + "/%s-%s-thunderstore.zip" % (MOD, VER))

# ---- (R) REPO дерево ----
R = ensure(BUILD + "/repo")
ensure(R + "/src"); ensure(R + "/translation/Translation/ru/Text")
shutil.copy2(SC + "/WKSourceTranslate.cs", R + "/src/WKSourceTranslate.cs")
shutil.copy2(SC + "/WKRusHelper.cs", R + "/src/WKRusHelper.cs")
shutil.copy2(SC + "/build_pkg.py", R + "/src/build_pkg.py")
write_text(R + "/translation/AutoTranslatorConfig.ini", cfg_text)
shutil.copy2(GROOT + "/oswald_ru_sdf", R + "/translation/oswald_ru_sdf")
put_translation(R + "/translation/Translation/ru/Text", dict_body)
write_text(R + "/README.md", README)
write_text(R + "/CHANGELOG.md", CHANGELOG)
write_text(R + "/LICENSE", LICENSE)
write_text(R + "/manifest.json", manifest)
shutil.copy2(T + "/icon.png", R + "/icon.png")
write_text(R + "/.gitignore", "build/\ndist/\n*.bak\n*.user\nobj/\nbin/\n")

# ---- сводка + проверки ----
def tree_count(p):
    n = 0; b = 0
    for root, d, files in os.walk(p):
        for f in files:
            n += 1; b += os.path.getsize(os.path.join(root, f))
    return n, b

print("\n=== АРТЕФАКТЫ ===")
print("icon:", icon_mode)
mn, mb = tree_count(M); tn, tb = tree_count(T)
print("manual zip:     %d файлов, распак %.1f MB -> zip %.1f MB" % (mn, mb/1e6, z_manual/1e6))
print("thunderstore:   %d файлов, распак %.1f MB -> zip %.1f MB" % (tn, tb/1e6, z_thunder/1e6))

# ВЕРИФИКАЦИЯ инвариантов
def check(cond, msg):
    print(("  OK  " if cond else "  FAIL ") + msg);
    if not cond: globals()["__bad__"] = True
print("\n=== ПРОВЕРКИ ===")
# нет мусора
for z, tag in ((DIST+"/%s-%s-manual.zip"%(MOD,VER),"manual"), (DIST+"/%s-%s-thunderstore.zip"%(MOD,VER),"thunder")):
    names = zipfile.ZipFile(z).namelist()
    check(not any("WKDump" in n for n in names), "%s: нет WKDump.dll" % tag)
    check(not any(n.endswith(".bak") for n in names), "%s: нет .bak" % tag)
    check(not any("/Translators/" in n for n in names), "%s: нет XUAT/Translators" % tag)
    check(any(n.endswith(SUB+"/Translation/ru/Text/"+DICT) or n.endswith("Translation/ru/Text/"+DICT) for n in names), "%s: словарь на месте" % tag)
    check(any("WKSourceTranslate.dll" in n for n in names), "%s: WKSourceTranslate.dll" % tag)
    check(any("WKRusHelper.dll" in n for n in names), "%s: WKRusHelper.dll" % tag)
    check(any("oswald_ru_sdf" in n for n in names), "%s: шрифт" % tag)
# thunderstore root: manifest/icon/readme в корне
tnames = zipfile.ZipFile(DIST+"/%s-%s-thunderstore.zip"%(MOD,VER)).namelist()
check("manifest.json" in tnames, "thunder: manifest.json в корне")
check("icon.png" in tnames, "thunder: icon.png в корне")
check("README.md" in tnames, "thunder: README.md в корне")
check(any(n.startswith("plugins/") for n in tnames), "thunder: plugins/ в корне")
check(any(n.startswith("config/") for n in tnames), "thunder: config/ в корне")
check(not any(n.startswith("BepInEx/") for n in tnames), "thunder: НЕТ обёртки BepInEx/ (override в корне)")
# manual root: loader + font
mnames = zipfile.ZipFile(DIST+"/%s-%s-manual.zip"%(MOD,VER)).namelist()
check("winhttp.dll" in mnames, "manual: winhttp.dll в корне")
check("oswald_ru_sdf" in mnames, "manual: шрифт в корне игры")
check(any(n.startswith("BepInEx/core/") for n in mnames), "manual: BepInEx/core/ есть")
print("\nИТОГ:", "ЕСТЬ ПРОБЛЕМЫ" if globals().get("__bad__") else "ВСЁ ЧИСТО")
print("dist:", DIST)
