using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text.RegularExpressions;
using BepInEx;
using BepInEx.Logging;
using HarmonyLib;
using UnityEngine;

// Перевод НА ИСТОЧНИКЕ: переводим голые поля Trinket/Perk (title/description/flavorText/unlockHint)
// ДО того как игра соберёт финальную строку с <shimmer>/числами. Тогда комбинаторика форм исчезает.
// XUAT остаётся страховкой: если объект переведён НЕ полностью — хук его НЕ трогает (all-or-nothing),
// и старый полный XUAT-ключ доперекрывает собранную англ-строку целиком (нет смеси рус+англ).
namespace WKSourceTranslate
{
    [BepInPlugin("wk.source.translate", "WK Source Translate", "1.0.0")]
    public class Plugin : BaseUnityPlugin
    {
        internal static Dictionary<string, string> Map = new Dictionary<string, string>(StringComparer.Ordinal);
        internal static ManualLogSource Log;

        void Awake()
        {
            Log = Logger;
            try { LoadDict(); }
            catch (Exception e) { Logger.LogError("[WKSrc] dict load failed: " + e); }
            try { new Harmony("wk.source.translate").PatchAll(); }
            catch (Exception e) { Logger.LogError("[WKSrc] patch failed: " + e); }
            Logger.LogInfo("[WKSrc] source-translate v1.0 loaded, dict=" + Map.Count);
        }

        static readonly Regex CYR = new Regex("[А-Яа-яЁё]", RegexOptions.Compiled);

        // dict рядом с DLL (упакованная manager-safe раскладка) -> иначе dev/legacy путь в BepInEx\Translation
        static string ResolveDictPath()
        {
            try
            {
                string dir = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
                if (!string.IsNullOrEmpty(dir))
                {
                    string p = Path.Combine(dir, "Translation", "ru", "Text", "_AutoGeneratedTranslations.txt");
                    if (File.Exists(p)) return p;
                }
            }
            catch { }
            return Path.Combine(Paths.BepInExRootPath, "Translation", "ru", "Text", "_AutoGeneratedTranslations.txt");
        }

        void LoadDict()
        {
            string path = ResolveDictPath();
            if (!File.Exists(path)) { Logger.LogWarning("[WKSrc] dict not found: " + path); return; }
            Logger.LogInfo("[WKSrc] dict: " + path);
            foreach (string raw in File.ReadAllLines(path))
            {
                string ln = raw;
                if (string.IsNullOrEmpty(ln) || ln.StartsWith("//") || ln.StartsWith("r:") || ln.StartsWith("sr:")) continue;
                // делим по первому НЕэкранированному '='
                int idx = -1;
                for (int i = 0; i < ln.Length; i++)
                {
                    if (ln[i] == '=' && (i == 0 || ln[i - 1] != '\\')) { idx = i; break; }
                }
                if (idx <= 0) continue;
                string k = Unesc(ln.Substring(0, idx));
                string v = Unesc(ln.Substring(idx + 1));
                if (k.Length == 0 || v.Length == 0 || v == k) continue;
                if (!CYR.IsMatch(v)) continue;          // только реальные русские переводы
                Map[k] = v;
            }
        }

        static string Unesc(string s)
        {
            return s.Replace("\\n", "\n").Replace("\\r", "").Replace("\\=", "=");
        }

        // перевод одной строки с защитой токенов; passthrough если ключа нет/опасно
        internal static string T(string s)
        {
            if (string.IsNullOrEmpty(s)) return s;
            string ru;
            if (!Map.TryGetValue(s, out ru)) return s;
            if (!TokenSafe(s, ru)) return s;
            return ru;
        }

        static readonly Regex TOK = new Regex("\\{.*?\\}", RegexOptions.Compiled);
        // набор {токенов} и счётчики (+)/(-) должны совпасть, иначе FillData/Replace сломается -> отказ
        static bool TokenSafe(string src, string dst)
        {
            var a = new List<string>(); foreach (Match m in TOK.Matches(src)) a.Add(m.Value); a.Sort();
            var b = new List<string>(); foreach (Match m in TOK.Matches(dst)) b.Add(m.Value); b.Sort();
            if (a.Count != b.Count) return false;
            for (int i = 0; i < a.Count; i++) if (a[i] != b[i]) return false;
            if (Count(src, "(+)") != Count(dst, "(+)")) return false;
            if (Count(src, "(-)") != Count(dst, "(-)")) return false;
            return true;
        }
        static int Count(string s, string sub)
        {
            int n = 0, i = 0;
            while ((i = s.IndexOf(sub, i, StringComparison.Ordinal)) >= 0) { n++; i += sub.Length; }
            return n;
        }
    }

    // идемпотентный кэш по instanceID — переводим объект один раз
    internal static class Cache
    {
        static readonly HashSet<int> done = new HashSet<int>();
        internal static bool First(int id) { return done.Add(id); }
    }

    // ---- TRINKET ----
    [HarmonyPatch(typeof(Trinket), nameof(Trinket.GetDescription))]
    static class Trinket_GetDescription
    {
        static void Prefix(Trinket __instance) { Hooks.TouchTrinket(__instance); }
        static void Postfix(ref string __result) { __result = Hooks.FixLabels(__result); }
    }

    [HarmonyPatch(typeof(Trinket), nameof(Trinket.GetLockedDescription))]
    static class Trinket_GetLockedDescription
    {
        static void Prefix(Trinket __instance) { Hooks.TouchTrinket(__instance); }
        static void Postfix(ref string __result) { __result = Hooks.FixLabels(__result); }
    }

    // ---- PERK ----
    [HarmonyPatch(typeof(Perk), nameof(Perk.GetDescription), new Type[] { typeof(bool), typeof(bool), typeof(bool), typeof(bool) })]
    static class Perk_GetDescription
    {
        static void Prefix(Perk __instance)
        {
            Hooks.TouchPerk(__instance);
            // обход IL `this = GetPlayer().GetPerk(id)` — метод читает поля из перка игрока, переводим и его
            try
            {
                var pl = ENT_Player.GetPlayer();
                if (pl != null && __instance != null)
                {
                    var rp = pl.GetPerk(__instance.id);
                    if (rp != null && rp != __instance) Hooks.TouchPerk(rp);
                }
            }
            catch { }
        }
    }

    [HarmonyPatch(typeof(Perk), nameof(Perk.GetTitle), new Type[] { typeof(bool) })]
    static class Perk_GetTitle
    {
        static void Prefix(Perk __instance) { Hooks.TouchPerk(__instance); }
    }

    internal static class Hooks
    {
        // all-or-nothing: переводим поля ТОЛЬКО если все непустые поля нашли перевод,
        // иначе не трогаем (XUAT-страховка доперекроет полную англ-строку).
        internal static void TouchTrinket(Trinket t)
        {
            try
            {
                if (t == null || !Cache.First(t.GetInstanceID())) return;
                string nt = Plugin.T(t.title), nd = Plugin.T(t.description), nf = Plugin.T(t.flavorText);
                bool ok = Hit(t.title, nt) && Hit(t.description, nd) && Hit(t.flavorText, nf);
                if (ok) { t.title = nt; t.description = nd; t.flavorText = nf; }
                // unlockHint независим (для GetLockedDescription)
                var pu = t.progressionUnlock;
                if (pu != null && Cache.First(pu.GetInstanceID()))
                {
                    string nh = Plugin.T(pu.unlockHint);
                    if (Hit(pu.unlockHint, nh)) pu.unlockHint = nh;
                }
            }
            catch (Exception e) { Plugin.Log?.LogWarning("[WKSrc] trinket: " + e.Message); }
        }

        internal static void TouchPerk(Perk p)
        {
            try
            {
                if (p == null || !Cache.First(p.GetInstanceID())) return;
                string nt = Plugin.T(p.title), nd = Plugin.T(p.description), nf = Plugin.T(p.flavorText);
                bool ok = Hit(p.title, nt) && Hit(p.description, nd) && Hit(p.flavorText, nf);
                if (ok) { p.title = nt; p.description = nd; p.flavorText = nf; }
            }
            catch (Exception e) { Plugin.Log?.LogWarning("[WKSrc] perk: " + e.Message); }
        }

        // поле «переведено успешно» = пустое (нечего переводить) ИЛИ строка изменилась (нашёлся перевод)
        static bool Hit(string src, string dst)
        {
            return string.IsNullOrEmpty(src) || !string.Equals(src, dst, StringComparison.Ordinal);
        }

        // литералы-метки, которые игра вшивает в сборку (не поля) -> чиним точечной заменой
        internal static string FixLabels(string s)
        {
            if (string.IsNullOrEmpty(s)) return s;
            s = s.Replace("<color=grey>Trinket:</color>", "<color=grey>Тринкет:</color>");
            s = s.Replace("<color=grey>Binding:</color>", "<color=grey>Привязка:</color>");
            s = s.Replace("<color=grey>Locked Trinket: </color>", "<color=grey>Закрытый тринкет: </color>");
            s = s.Replace("<color=grey>Locked Binding: </color>", "<color=grey>Закрытая привязка: </color>");
            s = s.Replace("Unlock Requirement: ", "Требование: ");
            return s;
        }
    }
}
