using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text.RegularExpressions;
using BepInEx;
using BepInEx.Logging;
using HarmonyLib;
using TMPro;
using UnityEngine;

// Перевод НА ИСТОЧНИКЕ: переводим голые поля Trinket/Perk (title/description/flavorText/unlockHint)
// ДО того как игра соберёт финальную строку с <shimmer>/числами. Тогда комбинаторика форм исчезает.
// XUAT остаётся страховкой: если объект переведён НЕ полностью — хук его НЕ трогает (all-or-nothing),
// и старый полный XUAT-ключ доперекрывает собранную англ-строку целиком (нет смеси рус+англ).
namespace WKSourceTranslate
{
    [BepInPlugin("wk.source.translate", "WK Source Translate", "1.0.2")]
    public class Plugin : BaseUnityPlugin
    {
        internal static Dictionary<string, string> Map = new Dictionary<string, string>(StringComparer.Ordinal);
        internal static ManualLogSource Log;

        void Awake()
        {
            Log = Logger;
            try { LoadDict(); }
            catch (Exception e) { Logger.LogError("[WKSrc] dict load failed: " + e); }
            try { new Harmony("wk.source.translate").PatchAll(); }
            catch (Exception e) { Logger.LogError("[WKSrc] patch failed: " + e); }
            Logger.LogInfo("[WKSrc] source-translate v1.0.2 loaded, dict=" + Map.Count);
        }

        internal static readonly Regex CYR = new Regex("[А-Яа-яЁё]", RegexOptions.Compiled);

        // dict рядом с DLL (упакованная manager-safe раскладка) -> иначе dev/legacy путь в BepInEx\Translation
        static string ResolveDictPath()
        {
            try
            {
                string dir = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
                if (!string.IsNullOrEmpty(dir))
                {
                    string p = Path.Combine(dir, "Translation", "ru", "Text", "_AutoGeneratedTranslations.txt");
                    if (File.Exists(p)) return p;
                }
            }
            catch { }
            return Path.Combine(Paths.BepInExRootPath, "Translation", "ru", "Text", "_AutoGeneratedTranslations.txt");
        }

        void LoadDict()
        {
            string path = ResolveDictPath();
            if (!File.Exists(path)) { Logger.LogWarning("[WKSrc] dict not found: " + path); return; }
            Logger.LogInfo("[WKSrc] dict: " + path);
            string[] rawLines;
            // FileShare.ReadWrite — XUAT может держать/писать файл в фоне, не падаем на IOException
            using (var fs = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
            using (var sr = new StreamReader(fs))
            {
                var acc = new List<string>();
                string line;
                while ((line = sr.ReadLine()) != null) acc.Add(line);
                rawLines = acc.ToArray();
            }
            foreach (string raw in rawLines)
            {
                string ln = raw;
                if (string.IsNullOrEmpty(ln) || ln.StartsWith("//") || ln.StartsWith("r:") || ln.StartsWith("sr:")) continue;
                // делим по первому НЕэкранированному '='
                int idx = -1;
                for (int i = 0; i < ln.Length; i++)
                {
                    if (ln[i] == '=' && (i == 0 || ln[i - 1] != '\\')) { idx = i; break; }
                }
                if (idx <= 0) continue;
                string k = Unesc(ln.Substring(0, idx));
                string v = Unesc(ln.Substring(idx + 1));
                if (k.Length == 0 || v.Length == 0 || v == k) continue;
                if (!CYR.IsMatch(v)) continue;          // только реальные русские переводы
                Map[k] = v;
            }
        }

        static string Unesc(string s)
        {
            return s.Replace("\\n", "\n").Replace("\\r", "").Replace("\\=", "=");
        }

        // перевод одной строки с защитой токенов; passthrough если ключа нет/опасно
        internal static string T(string s)
        {
            if (string.IsNullOrEmpty(s)) return s;
            string ru;
            if (!Map.TryGetValue(s, out ru)) return s;
            if (!TokenSafe(s, ru)) return s;
            return ru;
        }

        static readonly Regex TOK = new Regex("\\{.*?\\}", RegexOptions.Compiled);
        // набор {токенов} и счётчики (+)/(-) должны совпасть, иначе FillData/Replace сломается -> отказ
        static bool TokenSafe(string src, string dst)
        {
            var a = new List<string>(); foreach (Match m in TOK.Matches(src)) a.Add(m.Value); a.Sort();
            var b = new List<string>(); foreach (Match m in TOK.Matches(dst)) b.Add(m.Value); b.Sort();
            if (a.Count != b.Count) return false;
            for (int i = 0; i < a.Count; i++) if (a[i] != b[i]) return false;
            if (Count(src, "(+)") != Count(dst, "(+)")) return false;
            if (Count(src, "(-)") != Count(dst, "(-)")) return false;
            return true;
        }
        static int Count(string s, string sub)
        {
            int n = 0, i = 0;
            while ((i = s.IndexOf(sub, i, StringComparison.Ordinal)) >= 0) { n++; i += sub.Length; }
            return n;
        }

        // ============ P1/P2: текст В ОБХОД XUAT (ОС-лейблы exact-match + процедурные накладные) ============

        // exact-match из словаря -> иначе попытка как накладной -> иначе оригинал
        internal static string TranslateAny(string s)
        {
            if (string.IsNullOrEmpty(s)) return s;
            string ru;
            if (Map.TryGetValue(s, out ru) && TokenSafe(s, ru)) return ru;
            if (s.IndexOf("DELIVERY RECEIPT", StringComparison.Ordinal) >= 0) return ReceiptT(s);
            return s;
        }

        static readonly Regex RDATE = new Regex(@"^\s*\[\s*\d{1,2}\s*/\s*\d{1,2}\s*/\s*\d{2,4}\s*\]\s*$", RegexOptions.Compiled);

        // Накладная — фикс-записка: переводим ПОСТРОЧНО, дату/числовые строки пропускаем, неизвестные строки
        // оставляем как есть (частичный перевод). Смесь тут не страшна: для накладных нет полной XUAT-страховки.
        static string ReceiptT(string s)
        {
            try
            {
                string txt = s.IndexOf('\r') >= 0 ? s.Replace("\r", "") : s;
                string[] lines = txt.Split('\n');
                bool any = false;
                for (int i = 0; i < lines.Length; i++)
                {
                    string ln = lines[i];
                    if (ln.Trim().Length == 0 || RDATE.IsMatch(ln)) continue;     // пусто/дата -> насквозь
                    string r = LineT(ln);
                    if (r != null && !string.Equals(r, ln, StringComparison.Ordinal)) { lines[i] = r; any = true; }
                    // r == null (нет в словаре) -> строку не трогаем
                }
                return any ? string.Join("\n", lines) : s;
            }
            catch { return s; }
        }

        // строка накладной с сохранением отступа и маркера "- "; null = не нашли в словаре
        static string LineT(string ln)
        {
            int a = 0; while (a < ln.Length && (ln[a] == ' ' || ln[a] == '\t')) a++;
            string lead = ln.Substring(0, a);
            string rest = ln.Substring(a);
            string bullet = "";
            if (rest.StartsWith("- ", StringComparison.Ordinal)) { bullet = "- "; rest = rest.Substring(2); }
            string core = rest.TrimEnd();
            string tail = rest.Substring(core.Length);
            int colon = core.IndexOf(": ", StringComparison.Ordinal);
            if (colon > 0)                                          // "Label: value" -> метка + значение раздельно
            {
                string label = core.Substring(0, colon + 1);
                string val = core.Substring(colon + 2);
                string lru, vru;
                if (Map.TryGetValue(label, out lru) && TryVal(val, out vru))
                    return lead + bullet + lru + " " + vru + tail;
                return null;
            }
            string cru;
            if (Map.TryGetValue(core, out cru)) return lead + bullet + cru + tail;
            return null;
        }

        // значение "Acceptable, Minor Wear" — целиком ИЛИ по запятым
        static bool TryVal(string val, out string ru)
        {
            if (Map.TryGetValue(val, out ru)) return true;
            if (val.IndexOf(", ", StringComparison.Ordinal) >= 0)
            {
                string[] parts = val.Split(new string[] { ", " }, StringSplitOptions.None);
                string[] outp = new string[parts.Length];
                for (int i = 0; i < parts.Length; i++)
                {
                    string p;
                    if (!Map.TryGetValue(parts[i], out p)) { ru = null; return false; }
                    outp[i] = p;
                }
                ru = string.Join(", ", outp); return true;
            }
            ru = null; return false;
        }

    }

    // идемпотентный кэш по instanceID — переводим объект один раз
    internal static class Cache
    {
        static readonly HashSet<int> done = new HashSet<int>();
        internal static bool First(int id) { return done.Add(id); }
    }

    // ---- TRINKET ----
    [HarmonyPatch(typeof(Trinket), nameof(Trinket.GetDescription))]
    static class Trinket_GetDescription
    {
        static void Prefix(Trinket __instance) { Hooks.TouchTrinket(__instance); }
        static void Postfix(ref string __result) { __result = Hooks.FixLabels(__result); }
    }

    [HarmonyPatch(typeof(Trinket), nameof(Trinket.GetLockedDescription))]
    static class Trinket_GetLockedDescription
    {
        static void Prefix(Trinket __instance) { Hooks.TouchTrinket(__instance); }
        static void Postfix(ref string __result) { __result = Hooks.FixLabels(__result); }
    }

    // ---- PERK ----
    [HarmonyPatch(typeof(Perk), nameof(Perk.GetDescription), new Type[] { typeof(bool), typeof(bool), typeof(bool), typeof(bool) })]
    static class Perk_GetDescription
    {
        static void Prefix(Perk __instance)
        {
            Hooks.TouchPerk(__instance);
            // обход IL `this = GetPlayer().GetPerk(id)` — метод читает поля из перка игрока, переводим и его
            try
            {
                var pl = ENT_Player.GetPlayer();
                if (pl != null && __instance != null)
                {
                    var rp = pl.GetPerk(__instance.id);
                    if (rp != null && rp != __instance) Hooks.TouchPerk(rp);
                }
            }
            catch { }
        }
    }

    [HarmonyPatch(typeof(Perk), nameof(Perk.GetTitle), new Type[] { typeof(bool) })]
    static class Perk_GetTitle
    {
        static void Prefix(Perk __instance) { Hooks.TouchPerk(__instance); }
    }

    internal static class Hooks
    {
        // all-or-nothing: переводим поля ТОЛЬКО если все непустые поля нашли перевод,
        // иначе не трогаем (XUAT-страховка доперекроет полную англ-строку).
        internal static void TouchTrinket(Trinket t)
        {
            try
            {
                if (t == null || !Cache.First(t.GetInstanceID())) return;
                string nt = Plugin.T(t.title), nd = Plugin.T(t.description), nf = Plugin.T(t.flavorText);
                bool ok = Hit(t.title, nt) && Hit(t.description, nd) && Hit(t.flavorText, nf);
                if (ok) { t.title = nt; t.description = nd; t.flavorText = nf; }
                // unlockHint переводим ТОЛЬКО при ok (объект переведён целиком), иначе locked-описание
                // соберётся смесью (англ тело + рус подсказка), и XUAT её по полному англ-ключу не доперекроет.
                var pu = t.progressionUnlock;
                if (pu != null && ok && Cache.First(pu.GetInstanceID()))
                {
                    string nh = Plugin.T(pu.unlockHint);
                    if (Hit(pu.unlockHint, nh)) pu.unlockHint = nh;
                }
            }
            catch (Exception e) { Plugin.Log?.LogWarning("[WKSrc] trinket: " + e.Message); }
        }

        internal static void TouchPerk(Perk p)
        {
            try
            {
                if (p == null || !Cache.First(p.GetInstanceID())) return;
                string nt = Plugin.T(p.title), nd = Plugin.T(p.description), nf = Plugin.T(p.flavorText);
                bool ok = Hit(p.title, nt) && Hit(p.description, nd) && Hit(p.flavorText, nf);
                if (ok) { p.title = nt; p.description = nd; p.flavorText = nf; }
            }
            catch (Exception e) { Plugin.Log?.LogWarning("[WKSrc] perk: " + e.Message); }
        }

        // поле «переведено успешно» = пустое (нечего переводить) ИЛИ строка изменилась (нашёлся перевод)
        static bool Hit(string src, string dst)
        {
            return string.IsNullOrEmpty(src) || !string.Equals(src, dst, StringComparison.Ordinal);
        }

        // литералы-метки, которые игра вшивает в сборку (не поля) -> чиним точечной заменой
        internal static string FixLabels(string s)
        {
            // ГЕЙТ: нет кириллицы -> тело объекта НЕ переведено (ok=false). Метки НЕ русифицируем,
            // иначе выйдет смесь (англ тело + рус метки), которую XUAT по полному англ-ключу не доперекроет.
            if (string.IsNullOrEmpty(s) || !Plugin.CYR.IsMatch(s)) return s;
            s = s.Replace("<color=grey>Trinket:</color>", "<color=grey>Тринкет:</color>");
            s = s.Replace("<color=grey>Binding:</color>", "<color=grey>Привязка:</color>");
            s = s.Replace("<color=grey>Locked Trinket: </color>", "<color=grey>Закрытый тринкет: </color>");
            s = s.Replace("<color=grey>Locked Binding: </color>", "<color=grey>Закрытая привязка: </color>");
            s = s.Replace("Unlock Requirement: ", "Требование: ");
            return s;
        }
    }

    // ---- P1/P2: ловим текст через TMP_Text.SetText(string,...) — XUAT этот путь не цепляет
    // (потому ОС-лейблы и не попадали в дамп .text-сеттера). Exact-match -> мгновенно, без мигания скана. ----
    [HarmonyPatch]
    static class TMP_SetText_Hook
    {
        static IEnumerable<MethodBase> TargetMethods()
        {
            foreach (var m in typeof(TMP_Text).GetMethods(BindingFlags.Public | BindingFlags.Instance))
            {
                if (m.Name != "SetText") continue;
                var ps = m.GetParameters();
                if (ps.Length >= 1 && ps[0].ParameterType == typeof(string)) yield return m;
            }
        }
        // ref string __0 (а не object[] __args) — без boxing/аллокаций на горячих SetText-вызовах
        static void Prefix(ref string __0)
        {
            try
            {
                string s = __0;
                if (string.IsNullOrEmpty(s)) return;
                string ru = Plugin.TranslateAny(s);
                if (!ReferenceEquals(ru, s) && !string.Equals(ru, s, StringComparison.Ordinal)) __0 = ru;
            }
            catch { }
        }
    }
}
